import { FormEvent, useEffect, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { authService } from '../services/auth'
import { Project, projectsService, Requirement } from '../services/projects'
import { QualityDashboard, qualityService } from '../services/quality'
import './projects.css'

export default function QualityPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [requirements, setRequirements] = useState<Requirement[]>([])
  const [projectId, setProjectId] = useState('')
  const [dashboard, setDashboard] = useState<QualityDashboard | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { void loadProjects() }, [])
  useEffect(() => { if (projectId) void loadQuality(projectId) }, [projectId])
  if (!authService.hasToken()) return <Navigate to="/auth" replace />

  async function loadProjects() { try { const data = await projectsService.list(); setProjects(data); setProjectId(data[0]?.id || '') } catch { setError('No fue posible cargar los proyectos.') } }
  async function loadQuality(id: string) { try { setError(''); const [quality, reqs] = await Promise.all([qualityService.dashboard(id), projectsService.requirements(id)]); setDashboard(quality); setRequirements(reqs) } catch { setError('No fue posible cargar el centro de calidad.') } }
  async function createRisk(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!projectId) return; const form = new FormData(event.currentTarget); await qualityService.createRisk(projectId, { title: form.get('title'), description: form.get('description'), probability: Number(form.get('probability')), impact: Number(form.get('impact')), mitigation: form.get('mitigation') }); event.currentTarget.reset(); await loadQuality(projectId) }
  async function createTest(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!projectId) return; const form = new FormData(event.currentTarget); await qualityService.createTest(projectId, { requirementId: form.get('requirementId') || null, title: form.get('title'), preconditions: form.get('preconditions'), steps: form.get('steps'), expectedResult: form.get('expectedResult') }); event.currentTarget.reset(); await loadQuality(projectId) }
  async function createDefect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!projectId) return; const form = new FormData(event.currentTarget); await qualityService.createDefect(projectId, { requirementId: form.get('requirementId') || null, testCaseId: form.get('testCaseId') || null, title: form.get('title'), description: form.get('description'), severity: Number(form.get('severity')), priority: Number(form.get('priority')) }); event.currentTarget.reset(); await loadQuality(projectId) }

  return <main className="workspace-shell" aria-labelledby="quality-title">
    <header className="workspace-header"><div><p className="eyebrow">Fase 4 · Calidad y trazabilidad</p><h1 id="quality-title">Quality Center</h1><p>Riesgos, casos de prueba, defectos, métricas y cobertura de requisitos.</p></div><nav aria-label="Navegación del centro de calidad"><Link to="/projects">Proyectos</Link><Link to="/account">Mi cuenta</Link><Link to="/">Inicio</Link></nav></header>
    {error && <p className="workspace-error" role="alert" aria-live="assertive">{error}</p>}
    <section className="workspace-panel" aria-labelledby="active-project-label"><label id="active-project-label" htmlFor="quality-project">Proyecto activo</label><select id="quality-project" value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></section>

    {dashboard && <>
      <section className="lifecycle-grid" aria-label="Métricas de calidad"><article className="lifecycle-card"><h2>{dashboard.metrics.requirementCoveragePercent}%</h2><p>Cobertura de requisitos</p></article><article className="lifecycle-card"><h2>{dashboard.metrics.testPassRatePercent}%</h2><p>Tasa de pruebas aprobadas</p></article><article className="lifecycle-card"><h2>{dashboard.metrics.openDefects}</h2><p>Defectos abiertos</p></article><article className="lifecycle-card"><h2>{dashboard.metrics.highRisks}</h2><p>Riesgos altos</p></article></section>
      <section className="workspace-grid">
        <article className="workspace-panel"><h2>Registrar riesgo</h2><form className="workspace-form" onSubmit={createRisk}><label htmlFor="risk-title">Riesgo</label><input id="risk-title" name="title" required /><label htmlFor="risk-description">Descripción</label><textarea id="risk-description" name="description" /><label htmlFor="risk-probability">Probabilidad</label><select id="risk-probability" name="probability"><option value="1">Baja</option><option value="2">Media</option><option value="3">Alta</option></select><label htmlFor="risk-impact">Impacto</label><select id="risk-impact" name="impact"><option value="1">Bajo</option><option value="2">Medio</option><option value="3">Alto</option></select><label htmlFor="risk-mitigation">Plan de mitigación</label><textarea id="risk-mitigation" name="mitigation" /><button type="submit">Agregar riesgo</button></form></article>
        <article className="workspace-panel"><h2>Crear caso de prueba</h2><form className="workspace-form" onSubmit={createTest}><label htmlFor="test-requirement">Requisito relacionado</label><select id="test-requirement" name="requirementId"><option value="">Sin requisito</option>{requirements.map((r) => <option key={r.id} value={r.id}>{r.title}</option>)}</select><label htmlFor="test-title">Caso de prueba</label><input id="test-title" name="title" required /><label htmlFor="test-preconditions">Precondiciones</label><textarea id="test-preconditions" name="preconditions" /><label htmlFor="test-steps">Pasos</label><textarea id="test-steps" name="steps" /><label htmlFor="test-expected">Resultado esperado</label><textarea id="test-expected" name="expectedResult" /><button type="submit">Agregar caso</button></form></article>
        <article className="workspace-panel"><h2>Registrar defecto</h2><form className="workspace-form" onSubmit={createDefect}><label htmlFor="defect-requirement">Requisito relacionado</label><select id="defect-requirement" name="requirementId"><option value="">Sin requisito</option>{requirements.map((r) => <option key={r.id} value={r.id}>{r.title}</option>)}</select><label htmlFor="defect-test">Caso de prueba relacionado</label><select id="defect-test" name="testCaseId"><option value="">Sin caso de prueba</option>{dashboard.testCases.map((t) => <option key={t.id} value={t.id}>{t.title}</option>)}</select><label htmlFor="defect-title">Defecto</label><input id="defect-title" name="title" required /><label htmlFor="defect-description">Descripción</label><textarea id="defect-description" name="description" /><label htmlFor="defect-severity">Severidad</label><select id="defect-severity" name="severity"><option value="1">Baja</option><option value="2">Media</option><option value="3">Alta</option><option value="4">Crítica</option></select><label htmlFor="defect-priority">Prioridad</label><select id="defect-priority" name="priority"><option value="1">Baja</option><option value="2">Media</option><option value="3">Alta</option><option value="4">Urgente</option></select><button type="submit">Agregar defecto</button></form></article>
      </section>
      <section className="workspace-panel" aria-labelledby="traceability-title"><h2 id="traceability-title">Matriz de trazabilidad</h2><div className="requirement-list">{dashboard.traceability.map((row) => <article key={row.requirementId} className="requirement-card"><div className="requirement-meta"><span>{row.requirementStatus}</span><span>{row.covered ? 'Cubierto' : 'Sin cobertura'}</span></div><h3>{row.requirementTitle}</h3><p>{row.testCases} pruebas · {row.passedTests} aprobadas · {row.failedTests} fallidas · {row.openDefects} defectos abiertos</p></article>)}</div></section>
    </>}
  </main>
}
